# Microbe Metrics Cloudflare Worker Configuration
# Documentation: https://developers.cloudflare.com/workers/wrangler/configuration/

# Worker name and entry point
name = "microbe-metrics-worker"
main = "src/worker/worker.ts"
compatibility_date = "2023-11-01"

# R2 Bucket for genomics data storage (shared across environments)
[[r2_buckets]]
binding = "GENOMICS_DATA"
bucket_name = "genomics-analytics-data"
preview_bucket_name = "genomics-analytics-data-dev"

# KV Namespace for metadata caching (shared across environments)
[[kv_namespaces]]
binding = "METADATA_CACHE"
id = "60fd5e7242d1450ea8117ed155f141bc"
preview_id = "abb368c4b2504ffcb921804d27dbcfe3"

# Production environment configuration
[env.production]
name = "microbe-metrics-worker"
routes = [
  { pattern = "genomes.kenflynn.dev/api/*", zone_name = "kenflynn.dev" }
]

# Staging environment configuration
[env.staging]
name = "microbe-metrics-worker-staging"
routes = [
  { pattern = "staging.genomes.kenflynn.dev/api/*", zone_name = "kenflynn.dev" }
]

# Durable Objects for real-time analytics processing (optional - disabled for initial deployment)
# Uncomment when implementing stateful, real-time data processing
# [durable_objects]
# bindings = [
#   { name = "ANALYTICS_PROCESSOR", class_name = "AnalyticsProcessor" }
# ]

# Durable Object migrations (required when enabling Durable Objects)
# [[migrations]]
# tag = "v1"
# new_classes = [ "AnalyticsProcessor" ]

# Analytics Engine for observability (optional - disabled for initial deployment)
# Tracks worker performance metrics and custom analytics
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Assets directory for static files - DISABLED (frontend served via Cloudflare Pages)
# The worker only handles API endpoints, not static assets
# [assets]
# directory = ".svelte-kit/output/client"
# binding = "ASSETS"

# Scheduled event for daily data extraction from JGI
# Cron format: minute hour day month day-of-week
# Current: Daily at 6 AM UTC
[triggers]
crons = ["0 6 * * *"]

# Environment variables available in the worker
# These can be overridden per environment (production/staging)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
